[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ersilia-search"
version = "0.1.0"
description = "Search engine for the Ersilia Model Hub"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
  {name="Marina Miñarro-Lleonar", email="marina@ersilia.io"},
  {name="Miquel Duran Frigola", email = "miquel@ersilia.io"},
  {name="Ersilia Open Source Initiative", email = "hello@ersilia.io"}
]
requires-python = ">=3.10"

dependencies = [
  "fastapi==0.137.0",
  "click==8.1.8",
  "httpx==0.28.1",
  "rich==13.9.4",
  "pydantic==2.10.4",
]

[project.optional-dependencies]
dev = [
  "pytest==9.0.3",
  "ruff==0.15.13",
  "uvicorn==0.49.0"
]

[project.scripts]
ersilia_search = "ersilia_search.cli.create_cli:cli"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]

